on:
  pull_request:
    branches:
    - main
    - master
    - build
  push:
    branches:
    - main
    - master
    - build
name: Semgrep
jobs:
  semgrep:
    name: Scan
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: returntocorp/semgrep-action@v1
      with:
        config: s/ccxappsec:exposed-secret-key 
        publishToken: ${{ secrets.SEMGREP_APP_TOKEN }}
